-- +goose Up
CREATE SCHEMA IF NOT EXISTS vn_reg;
CREATE SCHEMA IF NOT EXISTS my_reg;
CREATE SCHEMA IF NOT EXISTS group_std;
CREATE SCHEMA IF NOT EXISTS local_policy;
CREATE SCHEMA IF NOT EXISTS local_sop;

-- +goose Down
DROP SCHEMA IF EXISTS local_sop CASCADE;
DROP SCHEMA IF EXISTS local_policy CASCADE;
DROP SCHEMA IF EXISTS group_std CASCADE;
DROP SCHEMA IF EXISTS my_reg CASCADE;
DROP SCHEMA IF EXISTS vn_reg CASCADE;
