-- +goose Up

-- M10 notifications + webhooks: user-facing notification rows generated by
-- detectors (conflict/staleness/overdue), webhook subscription registry for
-- external delivery, and a delivery audit log.  RLS is open (USING (true))
-- because filtering is application-level (by recipient_role/dept or
-- access_tier) rather than tier-gated.

CREATE TABLE graph.notification (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  finding_ref uuid NOT NULL REFERENCES graph.finding(id) ON DELETE CASCADE,
  kind text NOT NULL CHECK (kind IN ('conflict','staleness','overdue')),
  severity text NOT NULL DEFAULT 'medium' CHECK (severity IN ('critical','high','medium','low','info')),
  recipient_role text NOT NULL DEFAULT '',
  recipient_dept text NOT NULL DEFAULT '',
  title text NOT NULL DEFAULT '',
  read_at timestamptz,
  channels text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE graph.webhook_subscription (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  endpoint_url text NOT NULL,
  secret_ref text NOT NULL DEFAULT '',
  event_kinds text[] NOT NULL DEFAULT '{}',
  min_severity text NOT NULL DEFAULT 'medium' CHECK (min_severity IN ('critical','high','medium','low','info')),
  access_tier text NOT NULL DEFAULT 'public',
  active boolean NOT NULL DEFAULT true,
  created_by text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE graph.notification_delivery (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  notification_id uuid NOT NULL REFERENCES graph.notification(id) ON DELETE CASCADE,
  channel text NOT NULL CHECK (channel IN ('in_app','email','webhook')),
  target text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','sent','failed')),
  attempted_at timestamptz,
  response_code int,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes: finding lookup, unread fast-path, delivery by notification.
CREATE INDEX notification_finding_ref ON graph.notification (finding_ref);
CREATE INDEX notification_unread ON graph.notification (read_at) WHERE read_at IS NULL;
CREATE INDEX notification_delivery_notification_id ON graph.notification_delivery (notification_id);

-- Grants: SELECT to all three RLS roles.
GRANT SELECT ON graph.notification, graph.webhook_subscription, graph.notification_delivery
  TO mise_public, mise_group, mise_local;

-- RLS on notification: open to all roles (application-level filtering).
ALTER TABLE graph.notification ENABLE ROW LEVEL SECURITY;

CREATE POLICY public_read ON graph.notification FOR SELECT TO mise_public, mise_group, mise_local
  USING (true);

-- RLS on webhook_subscription: open to all roles.
ALTER TABLE graph.webhook_subscription ENABLE ROW LEVEL SECURITY;

CREATE POLICY public_read ON graph.webhook_subscription FOR SELECT TO mise_public, mise_group, mise_local
  USING (true);

-- RLS on notification_delivery: open to all roles (audit trail).
ALTER TABLE graph.notification_delivery ENABLE ROW LEVEL SECURITY;

CREATE POLICY public_read ON graph.notification_delivery FOR SELECT TO mise_public, mise_group, mise_local
  USING (true);

-- +goose Down

DROP POLICY IF EXISTS public_read ON graph.notification_delivery;
ALTER TABLE graph.notification_delivery DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS public_read ON graph.webhook_subscription;
ALTER TABLE graph.webhook_subscription DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS public_read ON graph.notification;
ALTER TABLE graph.notification DISABLE ROW LEVEL SECURITY;

REVOKE SELECT ON graph.notification, graph.webhook_subscription, graph.notification_delivery
  FROM mise_public, mise_group, mise_local;

DROP INDEX IF EXISTS graph.notification_delivery_notification_id;
DROP INDEX IF EXISTS graph.notification_unread;
DROP INDEX IF EXISTS graph.notification_finding_ref;

DROP TABLE IF EXISTS graph.notification_delivery;
DROP TABLE IF EXISTS graph.webhook_subscription;
DROP TABLE IF EXISTS graph.notification;
