name: Docs
on:
  push:
    paths: ['docs/**', '*.md', '.prettierrc.json', '.markdownlint-cli2.jsonc']
  pull_request:
    paths: ['docs/**', '*.md', '.prettierrc.json', '.markdownlint-cli2.jsonc']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - run: pnpm dlx markdownlint-cli2 "docs/**/*.md" "*.md"
      - run: pnpm dlx prettier --check "**/*.md" "*.md"
